#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep  3 02:11:26 2021

@author: fafa
"""

import scipy.io.wavfile as wav
from scipy.fftpack import fft,fftshift
import matplotlib.pyplot as plt

filename = 'fena_0001.wav' # nama file
fs, x = wav.read(filename) # membaca file wav
plt.plot(x)